import type { Metadata } from "next";
import { Recursive } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner";

const recursive = Recursive({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={recursive.className}>
        <main className="flex flex-col min-h-screen grainy-light  ">
          <Navbar />
          <div className="flex flex-1 gap-4 flex-col items-center ">
            {children}
          </div>
          <Toaster />
        </main>
      </body>
    </html>
  );
}
